INSERT INTO `countries` (`id`, `name`, `abbreviation`) VALUES
(9, 'Antigua and Barbuda', 'AG'),
(10, 'Argentina', 'AR'),
(12, 'Aruba', 'AW'),
(16, 'Bahamas', 'BS'),
(19, 'Barbados', 'BB'),
(22, 'Belize', 'BZ'),
(26, 'Bolivia', 'BO'),
(30, 'Brazil', 'BR'),
(38, 'Canada', 'CA'),
(43, 'Chile', 'CL'),
(44, 'China', 'CN'),
(47, 'Colombia', 'CO'),
(52, 'Costa Rica', 'CR'),
(55, 'Cuba', 'CU'),
(60, 'Dominica', 'DM'),
(61, 'Dominican Republic', 'DO'),
(63, 'Ecuador', 'EC'),
(65, 'El Salvador', 'SV'),
(75, 'France', 'FR'),
(76, 'French Guiana', 'GF'),
(82, 'Germany', 'DE'),
(85, 'Greece', 'GR'),
(87, 'Grenada', 'GD'),
(90, 'Guatemala', 'GT'),
(94, 'Guyana', 'GY'),
(95, 'Haiti', 'HT'),
(97, 'Honduras', 'HN'),
(98, 'Hong Kong', 'HK'),
(107, 'Italy', 'IT'),
(108, 'Jamaica', 'JM'),
(109, 'Japan', 'JP'),
(116, 'South Korea', 'KR'),
(133, 'Maldives', 'MV'),
(142, 'Mexico', 'MX'),
(145, 'Monaco', 'MC'),
(155, 'Netherlands', 'NL'),
(157, 'New Zealand', 'NZ'),
(158, 'Nicaragua', 'NI'),
(164, 'Norway', 'NO'),
(169, 'Panama', 'PA'),
(171, 'Paraguay', 'PY'),
(172, 'Peru', 'PE'),
(173, 'Phillipines', 'PH'),
(176, 'Portugal', 'PT'),
(177, 'Puerto Rico', 'PR'),
(181, 'Russia', 'RU'),
(183, 'Saint Helena', 'SH'),
(184, 'Saint Kitts and Nevis', 'KN'),
(185, 'Saint Lucia', 'LC'),
(186, 'Saint Pierre and Miquelon', 'PM'),
(187, 'Saint Vincent and the Grenadines', 'VC'),
(189, 'San Marino', 'SM'),
(196, 'Singapore', 'SG'),
(197, 'Slovakia', 'SK'),
(198, 'Slovenia', 'SI'),
(203, 'South Georgia and the South Sandwich Islands', 'GS'),
(205, 'España', 'ES'),
(208, 'Suriname', 'SR'),
(211, 'Sweden', 'SE'),
(212, 'Switzerland', 'CH'),
(214, 'Taiwan', 'TW'),
(217, 'Thailand', 'TH'),
(221, 'Trinidad and Tobago', 'TT'),
(223, 'Turkey', 'TR'),
(230, 'United Kingdom', 'GB'),
(231, 'United States', 'US'),
(232, 'United States Minor Outlying Islands', 'UM'),
(233, 'Uruguay', 'UY'),
(237, 'Venezuela', 'VE'),
(239, 'Virgin Islands, British', 'VG'),
(240, 'Virgin Islands, US', 'VI');